# Once an "Alpha" is properly tested and declared as production ready, a "pinned" version is created
# and published. Pinned versions are considered production ready, and the "latest" pinned version
# is pre-cached on https://www.bitrise.io/ Linux/Android Virtual Machines.
# Read more about how versions are handled in the README.md

FROM quay.io/bitriseio/android:alpha-v2020_03_19-02_19-b1967

CMD bitrise --version
